services:
  web:
    build: .
    command:
      - python manage.py runserver 0.0.0.0:5000
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
#

  db:
    image: postgres:alpine3.13
    env_file: "webapp.env"
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
